{% set python_min = '3.10' %}
{% set name = "conda-recipe-v2-schema" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prefix-dev/recipe-format/archive/v{{ version }}.tar.gz
  sha256: aa234973beaf184eaea1648f363604ed7cc8a94c5bd93852326e6b70c3e36281

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic

test:
  imports:
    - conda_recipe_v2_schema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/prefix-dev/recipe-format
  summary: Model for the recipe used to build conda packages
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Hofer-Julian
    - wolfv
